### ISSUE TITLE
AjaxFallbackLink#onClick() never gets called

### ISSUE THREAD

**Issue by lucrus73** [cooldatasoft/wicket-menu#1] opened 2015-06-16 15:13 UTC
I add a MenuItem to my MultiLevelCssMenu this way:

```
new MenuItem("item1", new AjaxFallbackLink<Void>("menuLink")
{
  @Override
  public void onClick(AjaxRequestTarget target)
  { ....
```

item1 shows up in the menu, but my onClick method never gets called even when I click on it.

**Comment by fmucar** [comment] 2015-06-16 15:17
Is there any exception/failure in the output?

**Comment by lucrus73** [comment] 2015-06-16 15:20
no, there isn't anything suspect

**Comment by fmucar** [comment] 2015-06-16 15:56
Would you please send sample code so I can replicate the problem and have a look. If you can create minimal sample app with the problem, that would make it much easier

**Comment by nicoliniyo** [comment] 2015-06-16 16:46
I'm really sorry, I've serached that code, but I do not have it any more.

2015-06-16 11:56 GMT-04:00 Fatih Mehmet UCAR notifications@github.com:

**Comment by lucrus73** [comment] 2015-06-17 06:51
I don't know what nicoliniyo is referring to. I'll make a quickstart showing the issue as soon as possible, but I can't just now, please stay tuned...

**Comment by lucrus73** [comment] 2015-08-04 17:53
While trying to understand what's going on, I noticed I'm using wicket-menu 6.9.1 and maven central has 6.12.0. However after updating my pom.xml from

    <dependency>
      <groupId>com.cooldatasoft</groupId>
      <artifactId>wicket-menu</artifactId>
      <version>6.9.1</version>
    </dependency>
    [...]
    <repository>
      <id>wicket-menu-release</id>
      <url>http://wicket-menu.googlecode.com/svn/maven/repo</url>
    </repository>
    <repository>
      <id>wicket-menu-snapshot</id>
      <url>http://wicket-menu.googlecode.com/svn/maven/snapshot-repo</url>
    </repository>

to

    <dependency>
      <groupId>com.cooldatasoft</groupId>
      <artifactId>wicket-menu</artifactId>
      <version>6.12.0</version>
    </dependency>

in order to get the ![latest version from maven central](http://search.maven.org/#artifactdetails%7Ccom.cooldatasoft%7Cwicket-menu%7C6.12.0%7Cjar), I get the following error from mvn:

    org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact com.cooldatasoft:wicket-menu-parent:pom:6.12.0 in Apache Nexus 

How should I edit my pom.xml in order to use the latest available wicket-menu version?

**Comment by cooldatasoft** [comment] 2015-08-04 22:06
Hi, I will fix it as soon as possible. It requires an update to the central maven repository.

**Comment by lucrus73** [comment] 2015-08-05 05:52
Ok, I've just opened issue #2 for that

**Comment by fmucar** [comment] 2015-08-09 00:04
I am gonna close this ticket as well. If you happen to have the issue again please let me know. For a sample implementation of ajax menu see the demo. It will give you an idea as there are a couple of small caveats with ajax links.

**Closed as completed by fmucar** 2015-08-09 00:04 UTC

**Comment by lucrus73** [comment] 2015-08-09 07:25
I'm still facing this issue. I did look at the demo, but unfortunately I couldn't get it to compile (problems with dependencies), so I couldn't test it either.
Looking at the demo source code, all I could notice is the fact I was using "menuLink" as value for id parameter to AjaxFallbackLink constructor, whereas the demo is using "subMenuLink". I've tried to change that in my code, but the problem persists.
I couldn't find any other substantial difference between my code and the demo code. You can [download a quickstart showing the issue here](http://www.sulweb.org/download/sparsi/issue1.zip). Would it be possible to document those caveats anywhere?

**Comment by fmucar** [comment] 2015-08-09 09:42
Thanks for the quickstart. Now I see what the problem is, I have found the bug. I will publish a fix. Please update your pom to get the latest version for wicket-menu. 

For caveats, yes, I have a plan for that to put into the javadocs and readme of the project page.

**Comment by lucrus73** [comment] 2015-08-09 10:13
Can you please reopen this issue so that I can track when the fix will be published? Thanks.

**Comment by fmucar** [comment] 2015-08-09 12:07
FIx is already published. It will take a couple of hours to appear in the central maven repo.
